import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer, Navbar, Container } from "@/components";
import ThemeContextProvider from "@/context/theme-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Container>
        <body className={`${inter.className} dark:bg-black`}>
          <ThemeContextProvider>
            <Navbar />
            {children}
            <Footer />
          </ThemeContextProvider>
        </body>
      </Container>
    </html>
  );
}
